Reimplement drag n drop
4teamwork/ftw.file pull request #115
Opened 2020-08-28 14:21 UTC by Nachtalb

- Reimplement the drag n drop feature
- Add journal entries (with name)
- Works on plone 4 and 5
- Improved styles and usability compared to before
- Cancelling and upload by hitting ESC now actually works
- Implementation based on a0f9c481a815979f378bf14bfa2089a868eaa70c

Upload and add a journal entry
---
![20200828_161545](https://user-images.githubusercontent.com/9467802/91578475-836c8380-e94a-11ea-8dec-be57a8fb8c92.gif)

Cancel upload with ESC
---
![20200828_161424](https://user-images.githubusercontent.com/9467802/91578441-78195800-e94a-11ea-9eed-4c79299722cc.gif)

2020-08-31 11:54 UTC, djowett-ftw reviewed
Since dropzone.js is included in Plone 5,  I really think we are missing an opportunity here to get rid of legacy JavaScript code as we move forward with this product - and reduce our technical debt.  Do you want to being supporting old style JS unnecessarily?
  If we need to support Plone 4, then granted, that's something to weigh up, but I think it's worth mentioning anyway.

I've not looked at it much, but it might be mostly a simple template thing using pat-upload.... 

```
    <div class="pat-upload" data-pat-upload='{"url": "/ajax-upload"}'>
       <p>Upload here</p>
    </div>
```
I also noticed that file_download_version fails in the Plone 4 history - but that may not be the fault of this patch

2020-08-31 11:54 UTC, djowett-ftw commented on ftw/file/browser/file_view.pt
> +              // AMD. Register as an anonymous module.
This ain't a module matey :-)

2020-08-31 12:03 UTC, Nachtalb commented on ftw/file/profiles/default/repositorytool.xml
> -      <policy name="at_edit_autoversion"/>
Removed that in https://github.com/4teamwork/ftw.file/commit/d61f6eb740fdf2de5d9066ad0686d608fcc5712d

2020-08-31 12:06 UTC, Nachtalb commented on ftw/file/browser/file_view.pt
> +              // AMD. Register as an anonymous module.
tbh that was copy-paste tbh

2020-09-01 06:51 UTC, maethu commented on ftw/file/browser/upload.py
> +            alsoProvides(self.request, IDisableCSRFProtection)
I agree i should be easy to add CSRF Protection here by adding the hidden input field on the detail view + use it in the POST/PATCH request.

2020-09-01 06:52 UTC, maethu commented
IMHO it looks good beside the disables CSRF Protection.

2020-09-01 07:21 UTC, Nachtalb commented
After discussing: we won't use the dropzone pattern from Plone 5. Like that we would either need to have to separate implementations (once Plone 5, once 4) or remove the feature in Plone 4. https://4teamwork.slack.com/archives/C0D69FKRD/p1598942668039500

2020-09-01 07:36 UTC, Nachtalb commented
@maethu @djowett-ftw I added CSRF protection as well as hardened the tests

2020-09-01 09:03 UTC, djowett-ftw requested changes
I get this on Plone5 (haven't tested Plone 4)

 ```Uncaught TypeError: e(...).overlay is not a function
    c ftw-file-compiled.js:154
    jQuery 5
    <anonymous> ftw-file-compiled.js:196
    execCb require.js:1696
    check require.js:883
    enable require.js:1176
    init require.js:788
    localRequire require.js:1460
    setTimeout handler*req.nextTick< require.js:1815
    localRequire require.js:1449
    requirejs require.js:1797
    <anonymous> ftw-file-compiled.js:93
    <anonymous> ftw-file-compiled.js:95
ftw-file-compiled.js:154
    c ftw-file-compiled.js:154
    jQuery 5
    <anonymous> ftw-file-compiled.js:196
    execCb require.js:1696
    check require.js:883
    enable require.js:1176
    init require.js:788
    localRequire require.js:1460
    (Async: setTimeout handler)
    nextTick require.js:1815
    localRequire require.js:1449
    requirejs require.js:1797
    <anonymous> ftw-file-compiled.js:93
    <anonymous> ftw-file-compiled.js:95
```

2020-09-01 09:07 UTC, maethu commented on ftw/file/resources/uploader.js
> +      if (dropzone === null) return;
Same with the SCSS.

2020-09-01 09:09 UTC, Nachtalb commented on ftw/file/resources/uploader.js
> +        formData.append('_authenticator', $('#dropzone [name="_authenticator"').val());
Damn my rebase failed. I had already fixed that but have lost it somehow 😂 Thanks!

2020-09-02 09:13 UTC, Nachtalb commented
@maethu as discussed I now fixed the download and tested it on plone 4 and 5

2020-09-02 09:15 UTC, maethu approved these changes
💚  AWESOME

2020-09-02 09:16 UTC, maethu commented
@Nachtalb BUT ADD A CHANGELOG ENTRY 😆

2020-09-03 07:06 UTC, merged

2020-09-09 14:25 UTC, djowett-ftw commented
> I get this on Plone5 (haven't tested Plone 4)
> 
> ```
>    c ftw-file-compiled.js:154
>    jQuery 5
>    <anonymous> ftw-file-compiled.js:196
>    execCb require.js:1696
>    check require.js:883
>    enable require.js:1176
>    init require.js:788
>    localRequire require.js:1460
>    setTimeout handler*req.nextTick< require.js:1815
>    localRequire require.js:1449
>    requirejs require.js:1797
>    <anonymous> ftw-file-compiled.js:93
>    <anonymous> ftw-file-compiled.js:95
> ftw-file-compiled.js:154
>    c ftw-file-compiled.js:154
>    jQuery 5
>    <anonymous> ftw-file-compiled.js:196
>    execCb require.js:1696
>    check require.js:883
>    enable require.js:1176
>    init require.js:788
>    localRequire require.js:1460
>    (Async: setTimeout handler)
>    nextTick require.js:1815
>    localRequire require.js:1449
>    requirejs require.js:1797
>    <anonymous> ftw-file-compiled.js:93
>    <anonymous> ftw-file-compiled.js:95
> ```

@Nachtalb Just checking - you did see this comment, right? I think it's fixed now on firefox, but would be good to hear you think so too :-)

2020-09-09 14:32 UTC, djowett-ftw commented
Sorry - that wasn't a good stacktrace I think.

This is the one I saw - which I just had again on https://devizug.zg.ch/web/behoerden/test/various-files/dsc_0210.jpg/file_view
```
Uncaught TypeError: e(...).overlay is not a function
    p https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:11877
    j https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:4
    add https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:4
    ready https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:4
    init https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:4
    m https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:4
    <anonymous> https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:11877
    execCb https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:1707
    check https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:894
    enable https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:1187
    init https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:799
    localRequire https://devizug.zg.ch/web/++plone++production/++unique++2020-09-03T16:17:44.662058/default.js:1471
default.js:11877:4411
```

<img width="1552" alt="Screenshot 2020-09-09 at 16 29 17" src="https://user-images.githubusercontent.com/54800639/92612278-029e7780-f2ba-11ea-958c-6192f0172f85.png">

2020-09-09 14:57 UTC, Nachtalb commented
@djowett-ftw fixed with https://github.com/4teamwork/ftw.file/pull/117